format = '''
[â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](bold red) $python$nodejs
[â”‚](bold red)[$directory](bold red)[$git_branch $git_commit$git_state $git_status](bold )
[â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](bold red)[ Ø¹](bold) 
'''



[username]
format = " [â•­â”€Kei]($style)"
style_user = "bold "
style_root = "bold "
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "../"




# Last param in the first line/row
# [cmd_duration]
# min_time = 1
# format = "took [$duration]($style)"
# disabled = falsefalse



# Prompt: optional param 1
# [time]
# format = " ğŸ•™ $time($style)\n"
# time_format = "%T"
# style = "bright"
# disabled = true

# Prompt: param 2 â””â”€
[character]
success_symbol = " [Î»](bold )"
# error_symbol = " [Ã—](bold )"
error_symbol = " [âŒ](bold )"


[docker_context]
symbol = "ïŒˆ "
format = "via [$symbol$context]($style) "
style = "bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false


[golang]
symbol = "î˜§ "

[memory_usage]
symbol = "ï¡š "

[package]
symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "
#pyenv_version_name = true
format = '[${symbol}(\($virtualenv\) )]($style)python (${version} )'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[nodejs]
format = "via [ï¢˜ Node.js $version](bold) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
# Before all the version info (python, nodejs, php, etc.)


# ! git ascending

[git_branch]
format = "[$symbol](bold)[$repository$name$branch](bold)"
symbol = "îœ¥ "

[git_commit]
format = "[\\($hash$tag\\)](bold) "
only_detached = false

[git_status]
style = "bold"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"

[git_state]
style = "bold"
